# smartdns.conf
# 监听端口（只监听 IPv4，避免与 IPv6 通配地址双栈冲突导致 bind 失败）
bind 0.0.0.0:5053 -no-rule-addr -no-rule-nameserver -no-dualstack-selection -force-aaaa-soa -no-speed-check -no-cache

#### log ####
log-num 0

#### 缓存 ####
cache-size 0

#### IPV6 #####
dualstack-ip-selection no
force-AAAA-SOA yes

#### 测速 ####
response-mode fastest-response

#### 并发保护 ####
max-query-limit 200

#### 其它 ####
# 强制指定 qtype 返回 SOA。禁用 SOA 65
force-qtype-SOA 65
# TCP 链接空闲超时时间
tcp-idle-time 120

#### 上游 DNS 服务 ####
# 此处利用 SmartDNS 的 EDNS 客户端子网，解析上海电信（202.96.209.133 为上海电信 DNS IP）优化的访问 IP。

# Global
# Google
server-tls 8.8.8.8:853
server-tls 8.8.4.4:853
# Cloudflare
server-tls 1.1.1.1:853
server-tls 1.0.0.1:853
# DNS.SB
server-tls 185.222.222.222:853
# Quad9
server-tls 9.9.9.11:853

# China
# Google
server-tls 8.8.4.4:853 -subnet 202.96.209.133
# Cloudflare
server-tls 1.0.0.1:853 -subnet 202.96.209.133
# DNS.SB
server-tls 185.222.222.222:853 -subnet 202.96.209.133
# AliDNS
server-tls 223.5.5.5:853 -subnet 202.96.209.133
# DNSPod
server-tls 1.12.12.12:853 -subnet 202.96.209.133
# 360
server-tls 101.226.4.6:853 -subnet 202.96.209.133
